In [7]:
from tensorflow.keras.layers import Input, Lambda, Dense, Flatten,Conv2D
from tensorflow.keras.models import Model
from tensorflow.keras.applications.vgg19 import VGG19
from tensorflow.keras.applications.resnet50 import preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator,load_img
from tensorflow.keras.models import Sequential
import numpy as np
from glob import glob
import matplotlib.pyplot as plt

In [8]:
IMAGE_SIZE = [224, 224]

train_path = 'images/Train'
valid_path = 'images/Test'

In [11]:
vgg19 = VGG19(input_shape=IMAGE_SIZE + [3], weights='imagenet', include_top=False)

In [13]:
vgg19.summary()

Model: "vgg19"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0     

In [14]:
for layer in vgg19.layers:
    layer.trainable = False

In [15]:
folders = glob('images/Train/*')


In [16]:
folders


['images/Train\\Parasite', 'images/Train\\Uninfected']

In [17]:
x = Flatten()(vgg19.output)

In [18]:
prediction = Dense(len(folders), activation='softmax')(x)

# create a model object
model = Model(inputs=vgg19.input, outputs=prediction)

In [19]:
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_2 (InputLayer)        [(None, 224, 224, 3)]     0         
                                                                 
 block1_conv1 (Conv2D)       (None, 224, 224, 64)      1792      
                                                                 
 block1_conv2 (Conv2D)       (None, 224, 224, 64)      36928     
                                                                 
 block1_pool (MaxPooling2D)  (None, 112, 112, 64)      0         
                                                                 
 block2_conv1 (Conv2D)       (None, 112, 112, 128)     73856     
                                                                 
 block2_conv2 (Conv2D)       (None, 112, 112, 128)     147584    
                                                                 
 block2_pool (MaxPooling2D)  (None, 56, 56, 128)       0     

code using cnn

In [20]:
from tensorflow.keras.layers import MaxPooling2D

In [21]:
model=Sequential()
model.add(Conv2D(filters=16,kernel_size=2,padding="same",activation="relu",input_shape=(224,224,3)))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters=32,kernel_size=2,padding="same",activation ="relu"))
model.add(MaxPooling2D(pool_size=2))
model.add(Conv2D(filters=64,kernel_size=2,padding="same",activation="relu"))
model.add(MaxPooling2D(pool_size=2))
model.add(Flatten())
model.add(Dense(500,activation="relu"))
model.add(Dense(2,activation="softmax"))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 conv2d (Conv2D)             (None, 224, 224, 16)      208       
                                                                 
 max_pooling2d (MaxPooling2D  (None, 112, 112, 16)     0         
 )                                                               
                                                                 
 conv2d_1 (Conv2D)           (None, 112, 112, 32)      2080      
                                                                 
 max_pooling2d_1 (MaxPooling  (None, 56, 56, 32)       0         
 2D)                                                             
                                                                 
 conv2d_2 (Conv2D)           (None, 56, 56, 64)        8256      
                                                                 
 max_pooling2d_2 (MaxPooling  (None, 28, 28, 64)       0

In [22]:
model.compile(
  loss='categorical_crossentropy',
  optimizer='adam',
  metrics=['accuracy']
)

In [23]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

train_datagen = ImageDataGenerator(rescale = 1./255,
                                   shear_range = 0.2,
                                   zoom_range = 0.2,
                                   horizontal_flip = True)

test_datagen = ImageDataGenerator(rescale = 1./255)

In [24]:
training_set = train_datagen.flow_from_directory('images/Train',
                                                 target_size = (224, 224),
                                                 batch_size = 32,
                                                 class_mode = 'categorical')

Found 416 images belonging to 2 classes.


In [25]:
test_set = test_datagen.flow_from_directory('images/Test',
                                            target_size = (224, 224),
                                            batch_size = 32,
                                            class_mode = 'categorical')

Found 134 images belonging to 2 classes.


In [28]:
r = model.fit(
  training_set,
  validation_data=test_set,
  epochs=10,
  steps_per_epoch=len(training_set),
  validation_steps=len(test_set)
)

Epoch 1/10
13/13 [==============================] - 16s 1s/step - loss: 0.6108 - accuracy: 0.6226 - val_loss: 0.7185 - val_accuracy: 0.4701
Epoch 2/10
13/13 [==============================] - 16s 1s/step - loss: 0.5476 - accuracy: 0.6947 - val_loss: 0.8447 - val_accuracy: 0.4328
Epoch 3/10
13/13 [==============================] - 16s 1s/step - loss: 0.6258 - accuracy: 0.6226 - val_loss: 0.7467 - val_accuracy: 0.4104
Epoch 4/10
13/13 [==============================] - 17s 1s/step - loss: 0.5703 - accuracy: 0.6827 - val_loss: 0.7868 - val_accuracy: 0.4179
Epoch 5/10
13/13 [==============================] - 20s 1s/step - loss: 0.5141 - accuracy: 0.7067 - val_loss: 0.9657 - val_accuracy: 0.3806
Epoch 6/10
13/13 [==============================] - 22s 2s/step - loss: 0.5053 - accuracy: 0.7452 - val_loss: 0.7768 - val_accuracy: 0.4552
Epoch 7/10
13/13 [==============================] - 17s 1s/step - loss: 0.4710 - accuracy: 0.7572 - val_loss: 0.7803 - val_accuracy: 0.4403
Epoch 8/10
13/13 [==

In [29]:
from tensorflow.keras.models import load_model

model.save('model_vgg19.h5')

In [30]:
y_pred = model.predict(test_set)
y_pred

5/5 [==============================] - 1s 136ms/step


array([[0.5951218 , 0.4048783 ],
       [0.8694177 , 0.13058232],
       [0.6015562 , 0.39844385],
       [0.19505888, 0.80494106],
       [0.452704  , 0.547296  ],
       [0.271038  , 0.728962  ],
       [0.50355476, 0.49644524],
       [0.32933033, 0.67066973],
       [0.46153006, 0.53847   ],
       [0.42587277, 0.5741272 ],
       [0.49746776, 0.50253224],
       [0.7473734 , 0.25262657],
       [0.49002764, 0.5099724 ],
       [0.37551415, 0.6244859 ],
       [0.49454975, 0.5054502 ],
       [0.31512824, 0.6848718 ],
       [0.44458872, 0.5554113 ],
       [0.16789612, 0.83210385],
       [0.4312808 , 0.5687192 ],
       [0.85131764, 0.14868234],
       [0.5118776 , 0.48812237],
       [0.3446026 , 0.65539736],
       [0.57627016, 0.42372987],
       [0.6871723 , 0.31282768],
       [0.27202243, 0.7279776 ],
       [0.52654254, 0.47345746],
       [0.2528879 , 0.7471121 ],
       [0.34355035, 0.65644974],
       [0.41554782, 0.58445215],
       [0.3475395 , 0.6524605 ],
       [0.

In [31]:
import numpy as np
y_pred = np.argmax(y_pred, axis=1)

In [32]:
y_pred

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       0, 1], dtype=int64)

In [33]:
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image

In [47]:
model=load_model('model_vgg19.h5')

In [49]:
img=image.load_img('images/Test/Uninfected/2.png',target_size=(224,224))

In [37]:
x=image.img_to_array(img)
x

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       ...,

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        ...,
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)

In [38]:
x=x/255

In [39]:
x=np.expand_dims(x,axis=0)
img_data=preprocess_input(x)
img_data.shape

(1, 224, 224, 3)

In [40]:
model.predict(img_data)

1/1 [==============================] - 0s 190ms/step


array([[1., 0.]], dtype=float32)

In [41]:
a=np.argmax(model.predict(img_data), axis=1)

1/1 [==============================] - 0s 67ms/step


In [50]:
if(a==1):
    print("Uninfected")
else:
    print("infected")

infected
